name: Create Release
on:
  push:
    branches:
      - main
jobs:
  create_release:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         node-version: [16.x]
     steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        uses: actions/setup-python@v2

      - name: Create Release
        run: |
          VERSION=$(echo ${{ github.ref }} | cut -d / -f 3)
          RELEASE_TAG="release-${{ env.VERSION }}"

          git tag -a ${{ env.RELEASE_TAG }} -m "Release ${{ env.VERSION }}"
          git push origin ${{ env.RELEASE_TAG }}
